### ISSUE TITLE
PusherBeamsPlugin.kt onNewIntent has incorrect argument type for overridden func

### ISSUE THREAD

**Issue by cameronhejazifar** [pusher/push-notifications-flutter#27] opened 2022-06-28 22:52 UTC
I am getting the following error when trying to build my application with the latest version of the pusher_beams flutter plugin (1.1.0). The errors I'm receiving are:

```
e: ./pub-cache/hosted/pub.dartlang.org/pusher_beams_android-1.1.0/android/src/main/kotlin/com/pusher/pusher_beams/PusherBeamsPlugin.kt: (23, 1): Class 'PusherBeamsPlugin' is not abstract and does not implement abstract member public abstract fun onNewIntent(p0: Intent): Boolean defined in io.flutter.plugin.common.PluginRegistry.NewIntentListener

e: ./pub-cache/hosted/pub.dartlang.org/pusher_beams_android-1.1.0/android/src/main/kotlin/com/pusher/pusher_beams/PusherBeamsPlugin.kt: (45, 5): 'onNewIntent' overrides nothing
```

It appears that the `onNewIntent` function in the `PusherBeamsPlugin.kt` file should not have a nullable Intent argument. Making this change in my local .pub-cache file allows me to successfully build and run the application using the new version.

```
override fun onNewIntent(intent: Intent): Boolean {
    handleIntent(context, intent)
    return false
}
```

**Comment by fbenevides** [comment] 2022-06-29 07:46
Hi, @cameronhejazifar, our team is investigating this issue. Could you please provide us what is the Android version are you using?

Thanks for the report.

**Comment by niglng** [comment] 2022-07-18 10:24
Am facing same for the past 4-days now. Thinking it was my code or declaration. Below is my configuration

Flutter (Channel stable, 3.0.4, on Microsoft Windows [Version 10.0.19044.1826])
Android toolchain - develop for Android devices (Android SDK version 33.0.0)
Android Studio (version 2021.1)

environment:
sdk: ">=2.17.1 <3.0.0"
flutter: ">=3.0.1"

I had to drop it to
environment:
sdk: ">=2.15.1 <3.0.0"

YET, the error continues.

**Comment by benjamin-tang-pusher** [comment] 2022-07-25 21:24
Did you add any other flutter libraries from other vendors during this time?

**Comment by luisfelipeas5** [comment] 2022-08-23 16:21
Same issue here. The issue is related to Flutter 3, because downgrading to Flutter 2.10.6, it works

**Comment by benjamin-tang-pusher** [comment] 2022-08-24 13:28
Fixed by https://github.com/pusher/push-notifications-flutter/pull/32

**Closed by benjamin-tang-pusher** 2022-08-24 13:28 UTC
