### ISSUE TITLE
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError - Null check operator used on a null value. Error thrown Instance of 'ErrorDescription'.

### ISSUE THREAD

**Issue by Arunachalam-G** [pusher/push-notifications-flutter#36] opened 2022-11-23 05:49 UTC
I experienced a crash in Pusher Beam plugin codes while using my flutter app. I added the crash logs below. Please check them and provide a solution to fix it. 

Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Null check operator used on a null value. Error thrown Instance of 'ErrorDescription'.
       at PusherBeams.handleCallback(pusher_beams.dart:290)
       at CallbackHandlerApi.setup.<fn>(method_channel_pusher_beams.dart:404)
       at CallbackHandlerApi.setup.<fn>(method_channel_pusher_beams.dart:391)
       at BasicMessageChannel.setMessageHandler.<fn>(platform_channel.dart:77)
       at BasicMessageChannel.setMessageHandler.<fn>(platform_channel.dart:76)
       at _DefaultBinaryMessenger.setMessageHandler.<fn>(binding.dart:380)
       at _DefaultBinaryMessenger.setMessageHandler.<fn>(binding.dart:377)

Additional Details:
1. Pusher Beam version - 1.0.2 
2. Platform - Android

**Comment by akshaydoshi2** [comment] 2022-12-07 12:25
Experiencing the same issue as mentioned by @Arunachalam-G while `addDeviceInterest` or `removeDeviceInterest`

======== Exception caught by services library ======================================================
The following _CastError was thrown during a platform message callback:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      PusherBeams.handleCallback (package:pusher_beams/pusher_beams.dart:329:44)
#1      CallbackHandlerApi.setup.<anonymous closure> (package:pusher_beams_platform_interface/method_channel_pusher_beams.dart:430:15)
#2      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:197:49)
#3      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:387:35)
#4      _invoke2 (dart:ui/hooks.dart:186:13)
#5      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#6      _Channel.push (dart:ui/channel_buffers.dart:132:31)
#7      ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#8      PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599:22)
#9      _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
====================================================================================================

**Comment by benjamin-tang-pusher** [comment] 2023-03-02 19:15
Hi, are either of you using the [flutter webview](https://pub.dev/packages/webview_flutter) plugin in your apps?

**Comment by akshaydoshi2** [comment] 2023-04-23 20:16
@benjamin-tang-pusher Hey, yes I am using the flutter webview plugin in my app.

**Comment by Arunachalam-G** [comment] 2023-04-24 03:36
> Hi, are either of you using the [flutter webview](https://pub.dev/packages/webview_flutter) plugin in your apps?

Hi, I'm not using [flutter webview](https://pub.dev/packages/webview_flutter) plugin in my app.

**Comment by benw-pusher** [comment] 2023-06-26 10:05
Hi @Arunachalam-G @akshaydoshi2 , are you able to share a short code snippet that replicates the issue? 
Does the issue happen every time you call addDeviceInterest or removeDeviceInterest?

**Comment by benw-pusher** [comment] 2023-08-09 15:07
Our suspicion is that this was caused by when also using the flutter webview plugin but the mixed responses appears to contradict this - however we haven't had any replication samples to help with investigation so we'll have to close this. However if you need further support here please contact us at https://support.pusher.com/hc/en-us/requests/new

**Closed by benw-pusher** 2023-08-09 15:07 UTC
